// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JsApiBaseResponse.proto

#ifndef PROTOBUF_JsApiBaseResponse_2eproto__INCLUDED
#define PROTOBUF_JsApiBaseResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace MMPro {
namespace micromsg {
class JsApiBaseResponse;
class JsApiBaseResponseDefaultTypeInternal;
extern JsApiBaseResponseDefaultTypeInternal _JsApiBaseResponse_default_instance_;
}  // namespace micromsg
}  // namespace MMPro

namespace MMPro {
namespace micromsg {

namespace protobuf_JsApiBaseResponse_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_JsApiBaseResponse_2eproto

// ===================================================================

class JsApiBaseResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MMPro.micromsg.JsApiBaseResponse) */ {
 public:
  JsApiBaseResponse();
  virtual ~JsApiBaseResponse();

  JsApiBaseResponse(const JsApiBaseResponse& from);

  inline JsApiBaseResponse& operator=(const JsApiBaseResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JsApiBaseResponse& default_instance();

  static inline const JsApiBaseResponse* internal_default_instance() {
    return reinterpret_cast<const JsApiBaseResponse*>(
               &_JsApiBaseResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(JsApiBaseResponse* other);

  // implements Message ----------------------------------------------

  inline JsApiBaseResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  JsApiBaseResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const JsApiBaseResponse& from);
  void MergeFrom(const JsApiBaseResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(JsApiBaseResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string _Errmsg = 2;
  bool has__errmsg() const;
  void clear__errmsg();
  static const int kErrmsgFieldNumber = 2;
  const ::std::string& _errmsg() const;
  void set__errmsg(const ::std::string& value);
  #if LANG_CXX11
  void set__errmsg(::std::string&& value);
  #endif
  void set__errmsg(const char* value);
  void set__errmsg(const char* value, size_t size);
  ::std::string* mutable__errmsg();
  ::std::string* release__errmsg();
  void set_allocated__errmsg(::std::string* _errmsg);

  // optional string _Errno = 3;
  bool has__errno() const;
  void clear__errno();
  static const int kErrnoFieldNumber = 3;
  const ::std::string& _errno() const;
  void set__errno(const ::std::string& value);
  #if LANG_CXX11
  void set__errno(::std::string&& value);
  #endif
  void set__errno(const char* value);
  void set__errno(const char* value, size_t size);
  ::std::string* mutable__errno();
  ::std::string* release__errno();
  void set_allocated__errno(::std::string* _errno);

  // optional uint32 _Errcode = 1;
  bool has__errcode() const;
  void clear__errcode();
  static const int kErrcodeFieldNumber = 1;
  ::google::protobuf::uint32 _errcode() const;
  void set__errcode(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MMPro.micromsg.JsApiBaseResponse)
 private:
  void set_has__errcode();
  void clear_has__errcode();
  void set_has__errmsg();
  void clear_has__errmsg();
  void set_has__errno();
  void clear_has__errno();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr _errmsg_;
  ::google::protobuf::internal::ArenaStringPtr _errno_;
  ::google::protobuf::uint32 _errcode_;
  friend struct protobuf_JsApiBaseResponse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// JsApiBaseResponse

// optional uint32 _Errcode = 1;
inline bool JsApiBaseResponse::has__errcode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void JsApiBaseResponse::set_has__errcode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void JsApiBaseResponse::clear_has__errcode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void JsApiBaseResponse::clear__errcode() {
  _errcode_ = 0u;
  clear_has__errcode();
}
inline ::google::protobuf::uint32 JsApiBaseResponse::_errcode() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiBaseResponse._Errcode)
  return _errcode_;
}
inline void JsApiBaseResponse::set__errcode(::google::protobuf::uint32 value) {
  set_has__errcode();
  _errcode_ = value;
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiBaseResponse._Errcode)
}

// optional string _Errmsg = 2;
inline bool JsApiBaseResponse::has__errmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JsApiBaseResponse::set_has__errmsg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JsApiBaseResponse::clear_has__errmsg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JsApiBaseResponse::clear__errmsg() {
  _errmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has__errmsg();
}
inline const ::std::string& JsApiBaseResponse::_errmsg() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiBaseResponse._Errmsg)
  return _errmsg_.GetNoArena();
}
inline void JsApiBaseResponse::set__errmsg(const ::std::string& value) {
  set_has__errmsg();
  _errmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiBaseResponse._Errmsg)
}
#if LANG_CXX11
inline void JsApiBaseResponse::set__errmsg(::std::string&& value) {
  set_has__errmsg();
  _errmsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MMPro.micromsg.JsApiBaseResponse._Errmsg)
}
#endif
inline void JsApiBaseResponse::set__errmsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has__errmsg();
  _errmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MMPro.micromsg.JsApiBaseResponse._Errmsg)
}
inline void JsApiBaseResponse::set__errmsg(const char* value, size_t size) {
  set_has__errmsg();
  _errmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MMPro.micromsg.JsApiBaseResponse._Errmsg)
}
inline ::std::string* JsApiBaseResponse::mutable__errmsg() {
  set_has__errmsg();
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.JsApiBaseResponse._Errmsg)
  return _errmsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JsApiBaseResponse::release__errmsg() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.JsApiBaseResponse._Errmsg)
  clear_has__errmsg();
  return _errmsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JsApiBaseResponse::set_allocated__errmsg(::std::string* _errmsg) {
  if (_errmsg != NULL) {
    set_has__errmsg();
  } else {
    clear_has__errmsg();
  }
  _errmsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _errmsg);
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.JsApiBaseResponse._Errmsg)
}

// optional string _Errno = 3;
inline bool JsApiBaseResponse::has__errno() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void JsApiBaseResponse::set_has__errno() {
  _has_bits_[0] |= 0x00000002u;
}
inline void JsApiBaseResponse::clear_has__errno() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void JsApiBaseResponse::clear__errno() {
  _errno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has__errno();
}
inline const ::std::string& JsApiBaseResponse::_errno() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiBaseResponse._Errno)
  return _errno_.GetNoArena();
}
inline void JsApiBaseResponse::set__errno(const ::std::string& value) {
  set_has__errno();
  _errno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiBaseResponse._Errno)
}
#if LANG_CXX11
inline void JsApiBaseResponse::set__errno(::std::string&& value) {
  set_has__errno();
  _errno_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MMPro.micromsg.JsApiBaseResponse._Errno)
}
#endif
inline void JsApiBaseResponse::set__errno(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has__errno();
  _errno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MMPro.micromsg.JsApiBaseResponse._Errno)
}
inline void JsApiBaseResponse::set__errno(const char* value, size_t size) {
  set_has__errno();
  _errno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MMPro.micromsg.JsApiBaseResponse._Errno)
}
inline ::std::string* JsApiBaseResponse::mutable__errno() {
  set_has__errno();
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.JsApiBaseResponse._Errno)
  return _errno_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JsApiBaseResponse::release__errno() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.JsApiBaseResponse._Errno)
  clear_has__errno();
  return _errno_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JsApiBaseResponse::set_allocated__errno(::std::string* _errno) {
  if (_errno != NULL) {
    set_has__errno();
  } else {
    clear_has__errno();
  }
  _errno_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _errno);
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.JsApiBaseResponse._Errno)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace micromsg
}  // namespace MMPro

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_JsApiBaseResponse_2eproto__INCLUDED
