// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JsApiBaseResponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "JsApiBaseResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MMPro {
namespace micromsg {
class JsApiBaseResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<JsApiBaseResponse> {
} _JsApiBaseResponse_default_instance_;

namespace protobuf_JsApiBaseResponse_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiBaseResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiBaseResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiBaseResponse, _errcode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiBaseResponse, _errmsg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiBaseResponse, _errno_),
  2,
  0,
  1,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 8, sizeof(JsApiBaseResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_JsApiBaseResponse_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "JsApiBaseResponse.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _JsApiBaseResponse_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _JsApiBaseResponse_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\027JsApiBaseResponse.proto\022\016MMPro.microms"
      "g\"F\n\021JsApiBaseResponse\022\020\n\010_Errcode\030\001 \001(\r"
      "\022\017\n\007_Errmsg\030\002 \001(\t\022\016\n\006_Errno\030\003 \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 113);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "JsApiBaseResponse.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_JsApiBaseResponse_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JsApiBaseResponse::kErrcodeFieldNumber;
const int JsApiBaseResponse::kErrmsgFieldNumber;
const int JsApiBaseResponse::kErrnoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JsApiBaseResponse::JsApiBaseResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_JsApiBaseResponse_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:MMPro.micromsg.JsApiBaseResponse)
}
JsApiBaseResponse::JsApiBaseResponse(const JsApiBaseResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  _errmsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has__errmsg()) {
    _errmsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._errmsg_);
  }
  _errno_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has__errno()) {
    _errno_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._errno_);
  }
  _errcode_ = from._errcode_;
  // @@protoc_insertion_point(copy_constructor:MMPro.micromsg.JsApiBaseResponse)
}

void JsApiBaseResponse::SharedCtor() {
  _cached_size_ = 0;
  _errmsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _errno_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _errcode_ = 0u;
}

JsApiBaseResponse::~JsApiBaseResponse() {
  // @@protoc_insertion_point(destructor:MMPro.micromsg.JsApiBaseResponse)
  SharedDtor();
}

void JsApiBaseResponse::SharedDtor() {
  _errmsg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _errno_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void JsApiBaseResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JsApiBaseResponse::descriptor() {
  protobuf_JsApiBaseResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_JsApiBaseResponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const JsApiBaseResponse& JsApiBaseResponse::default_instance() {
  protobuf_JsApiBaseResponse_2eproto::InitDefaults();
  return *internal_default_instance();
}

JsApiBaseResponse* JsApiBaseResponse::New(::google::protobuf::Arena* arena) const {
  JsApiBaseResponse* n = new JsApiBaseResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JsApiBaseResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MMPro.micromsg.JsApiBaseResponse)
  if (_has_bits_[0 / 32] & 3u) {
    if (has__errmsg()) {
      GOOGLE_DCHECK(!_errmsg_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*_errmsg_.UnsafeRawStringPointer())->clear();
    }
    if (has__errno()) {
      GOOGLE_DCHECK(!_errno_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*_errno_.UnsafeRawStringPointer())->clear();
    }
  }
  _errcode_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool JsApiBaseResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MMPro.micromsg.JsApiBaseResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 _Errcode = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has__errcode();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &_errcode_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string _Errmsg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__errmsg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->_errmsg().data(), this->_errmsg().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MMPro.micromsg.JsApiBaseResponse._Errmsg");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string _Errno = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__errno()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->_errno().data(), this->_errno().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MMPro.micromsg.JsApiBaseResponse._Errno");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MMPro.micromsg.JsApiBaseResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MMPro.micromsg.JsApiBaseResponse)
  return false;
#undef DO_
}

void JsApiBaseResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MMPro.micromsg.JsApiBaseResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 _Errcode = 1;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->_errcode(), output);
  }

  // optional string _Errmsg = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_errmsg().data(), this->_errmsg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.JsApiBaseResponse._Errmsg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->_errmsg(), output);
  }

  // optional string _Errno = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_errno().data(), this->_errno().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.JsApiBaseResponse._Errno");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->_errno(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MMPro.micromsg.JsApiBaseResponse)
}

::google::protobuf::uint8* JsApiBaseResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MMPro.micromsg.JsApiBaseResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 _Errcode = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->_errcode(), target);
  }

  // optional string _Errmsg = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_errmsg().data(), this->_errmsg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.JsApiBaseResponse._Errmsg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->_errmsg(), target);
  }

  // optional string _Errno = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_errno().data(), this->_errno().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.JsApiBaseResponse._Errno");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->_errno(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MMPro.micromsg.JsApiBaseResponse)
  return target;
}

size_t JsApiBaseResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MMPro.micromsg.JsApiBaseResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 7u) {
    // optional string _Errmsg = 2;
    if (has__errmsg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->_errmsg());
    }

    // optional string _Errno = 3;
    if (has__errno()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->_errno());
    }

    // optional uint32 _Errcode = 1;
    if (has__errcode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->_errcode());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JsApiBaseResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MMPro.micromsg.JsApiBaseResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const JsApiBaseResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const JsApiBaseResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MMPro.micromsg.JsApiBaseResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MMPro.micromsg.JsApiBaseResponse)
    MergeFrom(*source);
  }
}

void JsApiBaseResponse::MergeFrom(const JsApiBaseResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MMPro.micromsg.JsApiBaseResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has__errmsg();
      _errmsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._errmsg_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has__errno();
      _errno_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._errno_);
    }
    if (cached_has_bits & 0x00000004u) {
      _errcode_ = from._errcode_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void JsApiBaseResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MMPro.micromsg.JsApiBaseResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JsApiBaseResponse::CopyFrom(const JsApiBaseResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MMPro.micromsg.JsApiBaseResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JsApiBaseResponse::IsInitialized() const {
  return true;
}

void JsApiBaseResponse::Swap(JsApiBaseResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JsApiBaseResponse::InternalSwap(JsApiBaseResponse* other) {
  _errmsg_.Swap(&other->_errmsg_);
  _errno_.Swap(&other->_errno_);
  std::swap(_errcode_, other->_errcode_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JsApiBaseResponse::GetMetadata() const {
  protobuf_JsApiBaseResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_JsApiBaseResponse_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JsApiBaseResponse

// optional uint32 _Errcode = 1;
bool JsApiBaseResponse::has__errcode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void JsApiBaseResponse::set_has__errcode() {
  _has_bits_[0] |= 0x00000004u;
}
void JsApiBaseResponse::clear_has__errcode() {
  _has_bits_[0] &= ~0x00000004u;
}
void JsApiBaseResponse::clear__errcode() {
  _errcode_ = 0u;
  clear_has__errcode();
}
::google::protobuf::uint32 JsApiBaseResponse::_errcode() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiBaseResponse._Errcode)
  return _errcode_;
}
void JsApiBaseResponse::set__errcode(::google::protobuf::uint32 value) {
  set_has__errcode();
  _errcode_ = value;
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiBaseResponse._Errcode)
}

// optional string _Errmsg = 2;
bool JsApiBaseResponse::has__errmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void JsApiBaseResponse::set_has__errmsg() {
  _has_bits_[0] |= 0x00000001u;
}
void JsApiBaseResponse::clear_has__errmsg() {
  _has_bits_[0] &= ~0x00000001u;
}
void JsApiBaseResponse::clear__errmsg() {
  _errmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has__errmsg();
}
const ::std::string& JsApiBaseResponse::_errmsg() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiBaseResponse._Errmsg)
  return _errmsg_.GetNoArena();
}
void JsApiBaseResponse::set__errmsg(const ::std::string& value) {
  set_has__errmsg();
  _errmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiBaseResponse._Errmsg)
}
#if LANG_CXX11
void JsApiBaseResponse::set__errmsg(::std::string&& value) {
  set_has__errmsg();
  _errmsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MMPro.micromsg.JsApiBaseResponse._Errmsg)
}
#endif
void JsApiBaseResponse::set__errmsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has__errmsg();
  _errmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MMPro.micromsg.JsApiBaseResponse._Errmsg)
}
void JsApiBaseResponse::set__errmsg(const char* value, size_t size) {
  set_has__errmsg();
  _errmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MMPro.micromsg.JsApiBaseResponse._Errmsg)
}
::std::string* JsApiBaseResponse::mutable__errmsg() {
  set_has__errmsg();
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.JsApiBaseResponse._Errmsg)
  return _errmsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* JsApiBaseResponse::release__errmsg() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.JsApiBaseResponse._Errmsg)
  clear_has__errmsg();
  return _errmsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void JsApiBaseResponse::set_allocated__errmsg(::std::string* _errmsg) {
  if (_errmsg != NULL) {
    set_has__errmsg();
  } else {
    clear_has__errmsg();
  }
  _errmsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _errmsg);
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.JsApiBaseResponse._Errmsg)
}

// optional string _Errno = 3;
bool JsApiBaseResponse::has__errno() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void JsApiBaseResponse::set_has__errno() {
  _has_bits_[0] |= 0x00000002u;
}
void JsApiBaseResponse::clear_has__errno() {
  _has_bits_[0] &= ~0x00000002u;
}
void JsApiBaseResponse::clear__errno() {
  _errno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has__errno();
}
const ::std::string& JsApiBaseResponse::_errno() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiBaseResponse._Errno)
  return _errno_.GetNoArena();
}
void JsApiBaseResponse::set__errno(const ::std::string& value) {
  set_has__errno();
  _errno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiBaseResponse._Errno)
}
#if LANG_CXX11
void JsApiBaseResponse::set__errno(::std::string&& value) {
  set_has__errno();
  _errno_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MMPro.micromsg.JsApiBaseResponse._Errno)
}
#endif
void JsApiBaseResponse::set__errno(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has__errno();
  _errno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MMPro.micromsg.JsApiBaseResponse._Errno)
}
void JsApiBaseResponse::set__errno(const char* value, size_t size) {
  set_has__errno();
  _errno_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MMPro.micromsg.JsApiBaseResponse._Errno)
}
::std::string* JsApiBaseResponse::mutable__errno() {
  set_has__errno();
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.JsApiBaseResponse._Errno)
  return _errno_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* JsApiBaseResponse::release__errno() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.JsApiBaseResponse._Errno)
  clear_has__errno();
  return _errno_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void JsApiBaseResponse::set_allocated__errno(::std::string* _errno) {
  if (_errno != NULL) {
    set_has__errno();
  } else {
    clear_has__errno();
  }
  _errno_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _errno);
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.JsApiBaseResponse._Errno)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace micromsg
}  // namespace MMPro

// @@protoc_insertion_point(global_scope)
